export const tags = {
    tag_name: "Kshitij Halankar",
    tag_email: "kshitij.p.halankar@gmail.com",
    tag_phone: "+1 000 000 0000",
    tag_location : "Mississauga, ON, Canada",
    tag_dob : "1995-10-14",
    tag_nationality : "India",
    tag_gender : "Male",
    tag_job_title : "Full-stack Developer",
    tag_url : "https://kshitij-halankar.github.io/live-resume-1/",
    tag_years_old : "years old",
    tag_about_me : "About me",
    tag_projects : "Projects",
    tag_contact : "Contact",
    tag_share_text : "Hello, I'm a Full-stack Java Web Developer with 10+ years of experience designing web and mobile projects. Find out more in my live-resume!",
    tags_checkout: "CheckOut",
    tags_previous: "Previous",
    tags_next: "Next",
    tags_projects_publications: "Projects and Publications",
    tag_share_url : "https://kshitij-halankar.github.io/live-resume-1/",
    tag_copyright : "Copyright",
    tag_github_fork : "Fork on GitHub",
    tag_contact_success : "Thank you for contacting me, I'll reply to you very soon.",
    tag_contact_failure:
    "Sorry, there is an instability, try again later, or contact me via email or social media.",
    tag_welcome_img : "kshitij-illustration@2x.png",
    tag_contact_img: "./assets/template/contact/kshitij-contact.png",
    tag_dialog_phrase1: "Hey There!",
    tag_dialog_phrase2: "I'm Kshitij.",
    tag_dialog_phrase3: "Thanks for dropping by :)",
    tag_dialog_phrase4: "Scroll down to find more about me!",
    tag_description: "My path as a <i>programmer</i> has started at nineish years old, when I've fallen in love with <i>Logo</i>, an educational programming language used to captivate kids in the wonderful lands of <i>Programming</i>. I used to spend hours in a row trying to build figures and animations, using math and geometry. At that time, I just did not know the exciting challenges that were yet to come.<br><br>A few years later, I got an internship as a <i>Webmaster</i>, since then, I have never stopped. It has been more than a decade, where I'm having the chance to work with marvelous people, learning every day, traveling the world, and mainly, always making great friendships.<br><br>I had an entrepreneurship experience, when a friend of mine presented me <i>Magento</i>, an extremely popular e-commerce framework. After doing several courses and a lot of practice, I got contracts with agencies from São Paulo and Rio de Janeiro, Brazil. This entrepreneurship experience gave me the chance to see the other side of the coin, which contributed to sort of expand a bit more my consciousness as an employee.<br><br>Nowadays, I keep seeking new skills, learning and sharing my humble knowledge as much as possible.",
};
